require:
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - debug.rb
    - dev/**/*

Style/CombinableLoops:
  Exclude:
    - 'lib/sla/checker.rb'

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/PerceivedComplexity:
  Max: 12
